plugins {
    id 'org.springframework.boot'
}

dependencies {
    implementation project(':core')
    implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'org.springframework.boot:spring-boot-autoconfigure'
    implementation 'org.springframework.boot:spring-boot-starter-json'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.kafka:spring-kafka'
    implementation 'io.debezium:debezium-api:3.2.0.Final'
    implementation platform("software.amazon.awssdk:bom:2.21.2")
    implementation 'software.amazon.awssdk:s3'
    runtimeOnly 'com.mysql:mysql-connector-j'
    testImplementation 'org.springframework.kafka:spring-kafka-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'com.h2database:h2'
}
